tunnel: 64746180-e8db-4616-abfb-0433703b2645
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # Specific entry for NFL Picks app - must come before wildcard
  - hostname: footballpool.golfleaguemanager.app
    service: http://footballpool-nfl-picks-1:3001
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 20s
      keepAliveTimeout: 90s
      httpHostHeader: footballpool.golfleaguemanager.app
  # Support wildcard subdomains for multi-tenancy (existing apps)
  - hostname: "*.golfleaguemanager.app"
    service: http://localhost:4500
  # Fallback for the main domain
  - hostname: golfleaguemanager.app
    service: http://localhost:4500
  - service: http_status:404
