name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker compose build

    - name: Start services
      run: |
        docker compose up -d
        
    - name: Wait for services to start
      run: |
        echo "Waiting for services to start..."
        sleep 30

    - name: Health check
      run: |
        echo "Performing health check..."
        
        # Check if containers are running
        docker compose ps
        
        # Wait a bit more and try health check
        sleep 10
        
        # Try health check with retries
        for i in {1..5}; do
          echo "Health check attempt $i/5..."
          
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3001/api/games/current || echo "000")
          
          if [ "$response" = "200" ]; then
            echo "✅ Health check passed - Application is running"
            exit 0
          else
            echo "⏳ Health check failed (attempt $i/5) - HTTP status: $response"
            if [ $i -eq 5 ]; then
              echo "❌ All health check attempts failed"
              echo "Container logs:"
              docker compose logs --tail=20
              exit 1
            fi
            sleep 10
          fi
        done

    - name: Show container logs on failure
      if: failure()
      run: |
        echo "=== Container Status ==="
        docker compose ps
        echo "=== Container Logs ==="
        docker compose logs --tail=50

    - name: Cleanup
      if: always()
      run: |
        docker compose down
